# Logistic Regression
This dataset contains information of users in a social network. Those informations are the user id the gender the age and the estimated salary. A car company has just launched their brand new luxury SUV. And we're trying to see which of these users of the social network are going to buy this brand new SUV And the last column here tells If yes or no the user bought this SUV we are going to build a model that is going to predict if a user is going to buy or not the SUV based on two variables which are going to be the age and the estimated salary. So our matrix of feature is only going to be these two columns. We want to find some correlations between the age and the estimated salary of a user and his decision to purchase yes or no the SUV.


In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [16]:
dataset = pd.read_csv('/Users/haleyk/Documents/Daily_Log/100-Days-Of-ML-Code/datasets/Social_Network_Ads.csv')
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [17]:
X = dataset.iloc[:, [2, 3]].values
y = dataset.iloc[:, 4].values

In [18]:
X

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)   

In [20]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [21]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [22]:
y_pred = classifier.predict(X_test)

In [23]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [24]:
cm

array([[65,  3],
       [ 8, 24]])

In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X[ : , 0] = labelencoder_X.fit_transform(X[ : , 0])

# onehotencoder = OneHotEncoder(categorical_features = [0])
onehotencoder = OneHotEncoder()
X = onehotencoder.fit_transform(X).toarray()
labelencoder_Y = LabelEncoder()
Y =  labelencoder_Y.fit_transform(y)

Let us try to predict the model using the gender as one of the features.

In [25]:
X = dataset.iloc[:, [1, 2]].values
y = dataset.iloc[:, 4].values

In [26]:
X

array([['Male', 19],
       ['Male', 35],
       ['Female', 26],
       ['Female', 27],
       ['Male', 19],
       ['Male', 27],
       ['Female', 27],
       ['Female', 32],
       ['Male', 25],
       ['Female', 35],
       ['Female', 26],
       ['Female', 26],
       ['Male', 20],
       ['Male', 32],
       ['Male', 18],
       ['Male', 29],
       ['Male', 47],
       ['Male', 45],
       ['Male', 46],
       ['Female', 48],
       ['Male', 45],
       ['Female', 47],
       ['Male', 48],
       ['Female', 45],
       ['Male', 46],
       ['Male', 47],
       ['Male', 49],
       ['Female', 47],
       ['Male', 29],
       ['Male', 31],
       ['Male', 31],
       ['Female', 27],
       ['Female', 21],
       ['Female', 28],
       ['Male', 27],
       ['Male', 35],
       ['Female', 33],
       ['Male', 30],
       ['Female', 26],
       ['Female', 27],
       ['Female', 27],
       ['Female', 33],
       ['Male', 35],
       ['Male', 30],
       ['Female', 28],
       ['Male',

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)   

In [28]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

ValueError: could not convert string to float: 'Female'

In [29]:
X = dataset.iloc[:, [1, 2]].values
y = dataset.iloc[:, 4].values

In [30]:
X # we need to change the male and female into label encoder

array([['Male', 19],
       ['Male', 35],
       ['Female', 26],
       ['Female', 27],
       ['Male', 19],
       ['Male', 27],
       ['Female', 27],
       ['Female', 32],
       ['Male', 25],
       ['Female', 35],
       ['Female', 26],
       ['Female', 26],
       ['Male', 20],
       ['Male', 32],
       ['Male', 18],
       ['Male', 29],
       ['Male', 47],
       ['Male', 45],
       ['Male', 46],
       ['Female', 48],
       ['Male', 45],
       ['Female', 47],
       ['Male', 48],
       ['Female', 45],
       ['Male', 46],
       ['Male', 47],
       ['Male', 49],
       ['Female', 47],
       ['Male', 29],
       ['Male', 31],
       ['Male', 31],
       ['Female', 27],
       ['Female', 21],
       ['Female', 28],
       ['Male', 27],
       ['Male', 35],
       ['Female', 33],
       ['Male', 30],
       ['Female', 26],
       ['Female', 27],
       ['Female', 27],
       ['Female', 33],
       ['Male', 35],
       ['Male', 30],
       ['Female', 28],
       ['Male',

In [31]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[ : , 0] = labelencoder_X.fit_transform(X[ : , 0])
X

array([[1, 19],
       [1, 35],
       [0, 26],
       [0, 27],
       [1, 19],
       [1, 27],
       [0, 27],
       [0, 32],
       [1, 25],
       [0, 35],
       [0, 26],
       [0, 26],
       [1, 20],
       [1, 32],
       [1, 18],
       [1, 29],
       [1, 47],
       [1, 45],
       [1, 46],
       [0, 48],
       [1, 45],
       [0, 47],
       [1, 48],
       [0, 45],
       [1, 46],
       [1, 47],
       [1, 49],
       [0, 47],
       [1, 29],
       [1, 31],
       [1, 31],
       [0, 27],
       [0, 21],
       [0, 28],
       [1, 27],
       [1, 35],
       [0, 33],
       [1, 30],
       [0, 26],
       [0, 27],
       [0, 27],
       [0, 33],
       [1, 35],
       [1, 30],
       [0, 28],
       [1, 23],
       [1, 25],
       [0, 27],
       [1, 30],
       [0, 31],
       [0, 24],
       [0, 18],
       [0, 29],
       [0, 35],
       [0, 27],
       [0, 24],
       [0, 23],
       [1, 28],
       [1, 22],
       [0, 32],
       [1, 27],
       [1, 25],
       [